//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorhniiFoundationWallet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DorhniiFoundationWallet.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string _String {
            get {
                return ResourceManager.GetString("#String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string fggf {
            get {
                return ResourceManager.GetString("fggf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will reach out to you as soon as possible.
        /// </summary>
        internal static string msgAfterMailSend {
            get {
                return ResourceManager.GetString("msgAfterMailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password must be same..
        /// </summary>
        internal static string msgConfirmPassword {
            get {
                return ResourceManager.GetString("msgConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to enable Touch Id or Face Id..
        /// </summary>
        internal static string msgDoYouWantToEnableTouchOrFaceId {
            get {
                return ResourceManager.GetString("msgDoYouWantToEnableTouchOrFaceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords fields cannot be empty..
        /// </summary>
        internal static string msgEmptyPasswords {
            get {
                return ResourceManager.GetString("msgEmptyPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to Exit the Application ?.
        /// </summary>
        internal static string msgExit {
            get {
                return ResourceManager.GetString("msgExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection not found. Please check &amp; try again..
        /// </summary>
        internal static string msgNetworkIssueMessage {
            get {
                return ResourceManager.GetString("msgNetworkIssueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password is wrong.
        /// </summary>
        internal static string msgOldPasswordAlert {
            get {
                return ResourceManager.GetString("msgOldPasswordAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Password .
        /// </summary>
        internal static string msgPasswordAlert {
            get {
                return ResourceManager.GetString("msgPasswordAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        internal static string msgPasswordChanged {
            get {
                return ResourceManager.GetString("msgPasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 8 max 16 characters and having letters or numbers or both..
        /// </summary>
        internal static string msgPasswordValidation {
            get {
                return ResourceManager.GetString("msgPasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all seeds to confirm.
        /// </summary>
        internal static string msgRestoreSeedAlert {
            get {
                return ResourceManager.GetString("msgRestoreSeedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tap all the Seed.
        /// </summary>
        internal static string msgSeedEntryAlert {
            get {
                return ResourceManager.GetString("msgSeedEntryAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed Phrase entry fields cannot be empty.
        /// </summary>
        internal static string msgSeedEntryError {
            get {
                return ResourceManager.GetString("msgSeedEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Save the Seed Phrase..
        /// </summary>
        internal static string msgSeedPhraseSave {
            get {
                return ResourceManager.GetString("msgSeedPhraseSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error occurred, please try again..
        /// </summary>
        internal static string msgTechnicalErrorOccurred {
            get {
                return ResourceManager.GetString("msgTechnicalErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter or Scan for wallet address.
        /// </summary>
        internal static string msgWalletAdressAlert {
            get {
                return ResourceManager.GetString("msgWalletAdressAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ff.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stake.
        /// </summary>
        internal static string tstStake {
            get {
                return ResourceManager.GetString("tstStake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10% APR.
        /// </summary>
        internal static string txt10APR {
            get {
                return ResourceManager.GetString("txt10APR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 MONTHS.
        /// </summary>
        internal static string txt12Month {
            get {
                return ResourceManager.GetString("txt12Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15% APR.
        /// </summary>
        internal static string txt15APR {
            get {
                return ResourceManager.GetString("txt15APR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20% APR.
        /// </summary>
        internal static string txt20APR {
            get {
                return ResourceManager.GetString("txt20APR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 MONTHS.
        /// </summary>
        internal static string txt3Month {
            get {
                return ResourceManager.GetString("txt3Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4% APR.
        /// </summary>
        internal static string txt4APR {
            get {
                return ResourceManager.GetString("txt4APR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 MONTHS.
        /// </summary>
        internal static string txt6Mnoth {
            get {
                return ResourceManager.GetString("txt6Mnoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9% APR.
        /// </summary>
        internal static string txt9APR {
            get {
                return ResourceManager.GetString("txt9APR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string txtAccounts {
            get {
                return ResourceManager.GetString("txtAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will reach you shortly..
        /// </summary>
        internal static string txtAcknowledgeSupport {
            get {
                return ResourceManager.GetString("txtAcknowledgeSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Wallet.
        /// </summary>
        internal static string txtAddWallet {
            get {
                return ResourceManager.GetString("txtAddWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string txtAlert {
            get {
                return ResourceManager.GetString("txtAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string txtAmount {
            get {
                return ResourceManager.GetString("txtAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APR.
        /// </summary>
        internal static string txtAPR {
            get {
                return ResourceManager.GetString("txtAPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APY,.
        /// </summary>
        internal static string txtApy {
            get {
                return ResourceManager.GetString("txtApy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHENTICATION.
        /// </summary>
        internal static string txtAuthentication {
            get {
                return ResourceManager.GetString("txtAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string txtBack {
            get {
                return ResourceManager.GetString("txtBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        internal static string txtBackCapital {
            get {
                return ResourceManager.GetString("txtBackCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string txtBalance {
            get {
                return ResourceManager.GetString("txtBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BALANCE.
        /// </summary>
        internal static string txtBalanceCapital {
            get {
                return ResourceManager.GetString("txtBalanceCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ 12,34,5565.00.
        /// </summary>
        internal static string txtBalanceDigit {
            get {
                return ResourceManager.GetString("txtBalanceDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $12,780.89.
        /// </summary>
        internal static string txtBalanceStake {
            get {
                return ResourceManager.GetString("txtBalanceStake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biometrics Login.
        /// </summary>
        internal static string txtBiometricsLogin {
            get {
                return ResourceManager.GetString("txtBiometricsLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRIDGES.
        /// </summary>
        internal static string txtBRIDGES {
            get {
                return ResourceManager.GetString("txtBRIDGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string txtCancel {
            get {
                return ResourceManager.GetString("txtCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string txtChangePassword {
            get {
                return ResourceManager.GetString("txtChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Amount.
        /// </summary>
        internal static string txtCharge {
            get {
                return ResourceManager.GetString("txtCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM.
        /// </summary>
        internal static string txtCONFIRM {
            get {
                return ResourceManager.GetString("txtCONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string txtConfirmPassword {
            get {
                return ResourceManager.GetString("txtConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string txtCopy {
            get {
                return ResourceManager.GetString("txtCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string txtCreate {
            get {
                return ResourceManager.GetString("txtCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE.
        /// </summary>
        internal static string txtCreateCapital {
            get {
                return ResourceManager.GetString("txtCreateCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Wallet.
        /// </summary>
        internal static string txtCreateWallet {
            get {
                return ResourceManager.GetString("txtCreateWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DHN.
        /// </summary>
        internal static string txtDHN {
            get {
                return ResourceManager.GetString("txtDHN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string txtDollar {
            get {
                return ResourceManager.GetString("txtDollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOHRNII.
        /// </summary>
        internal static string txtDORHNIICapital {
            get {
                return ResourceManager.GetString("txtDORHNIICapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string txtDuraction {
            get {
                return ResourceManager.GetString("txtDuraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string txtEditProfile {
            get {
                return ResourceManager.GetString("txtEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Password Fields.
        /// </summary>
        internal static string txtEmptyPasswords {
            get {
                return ResourceManager.GetString("txtEmptyPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string txtEnable {
            get {
                return ResourceManager.GetString("txtEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Fingerprint or face Id login.
        /// </summary>
        internal static string txtEnableFingerprint {
            get {
                return ResourceManager.GetString("txtEnableFingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Touch Face Id.
        /// </summary>
        internal static string txtEnableTouchFaceId {
            get {
                return ResourceManager.GetString("txtEnableTouchFaceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date -.
        /// </summary>
        internal static string txtEndDate {
            get {
                return ResourceManager.GetString("txtEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END DATE.
        /// </summary>
        internal static string txtEndDateButton {
            get {
                return ResourceManager.GetString("txtEndDateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Amount.
        /// </summary>
        internal static string txtEnterAmount {
            get {
                return ResourceManager.GetString("txtEnterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        internal static string txtEnterPassword {
            get {
                return ResourceManager.GetString("txtEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Seed Phrase.
        /// </summary>
        internal static string txtEnterSeedPhrase {
            get {
                return ResourceManager.GetString("txtEnterSeedPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Wallet name.
        /// </summary>
        internal static string txtEnterWalletName {
            get {
                return ResourceManager.GetString("txtEnterWalletName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER YOUR.
        /// </summary>
        internal static string txtENTERYOUR {
            get {
                return ResourceManager.GetString("txtENTERYOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERC-20.
        /// </summary>
        internal static string txtERC20 {
            get {
                return ResourceManager.GetString("txtERC20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Alert ?.
        /// </summary>
        internal static string txtExitAlert {
            get {
                return ResourceManager.GetString("txtExitAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint and Face Id.
        /// </summary>
        internal static string txtFaceId {
            get {
                return ResourceManager.GetString("txtFaceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FACE ID.
        /// </summary>
        internal static string txtFaceIDCapital {
            get {
                return ResourceManager.GetString("txtFaceIDCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look at camera for Face ID.
        /// </summary>
        internal static string txtFaceIdNotice {
            get {
                return ResourceManager.GetString("txtFaceIdNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        internal static string txtFee {
            get {
                return ResourceManager.GetString("txtFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place your finger for fingerprint reading.
        /// </summary>
        internal static string txtFinferprintNotice {
            get {
                return ResourceManager.GetString("txtFinferprintNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Fingerprint or Face ID.
        /// </summary>
        internal static string txtFingerprint {
            get {
                return ResourceManager.GetString("txtFingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINGERPRINT.
        /// </summary>
        internal static string txtFingerprintCapital {
            get {
                return ResourceManager.GetString("txtFingerprintCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figerprint.
        /// </summary>
        internal static string txtFingerprntLabel {
            get {
                return ResourceManager.GetString("txtFingerprntLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLEXIBLE.
        /// </summary>
        internal static string txtFlexible {
            get {
                return ResourceManager.GetString("txtFlexible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas fees.
        /// </summary>
        internal static string txtGasFee {
            get {
                return ResourceManager.GetString("txtGasFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET HELP.
        /// </summary>
        internal static string txtGe {
            get {
                return ResourceManager.GetString("txtGe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERAL.
        /// </summary>
        internal static string txtGENERAL {
            get {
                return ResourceManager.GetString("txtGENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Help.
        /// </summary>
        internal static string txtGetHelp {
            get {
                return ResourceManager.GetString("txtGetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can we help you....
        /// </summary>
        internal static string txtHowCanI {
            get {
                return ResourceManager.GetString("txtHowCanI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How we use your data.
        /// </summary>
        internal static string txtHowToUse {
            get {
                return ResourceManager.GetString("txtHowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please paste or enter your private key.
        /// </summary>
        internal static string txtImportPrivateKey {
            get {
                return ResourceManager.GetString("txtImportPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please paste or enter your seed phrase.
        /// </summary>
        internal static string txtImportSeedPhrase1 {
            get {
                return ResourceManager.GetString("txtImportSeedPhrase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to which you saved earlier.
        /// </summary>
        internal static string txtImportSeedPhrasePrivateKey1 {
            get {
                return ResourceManager.GetString("txtImportSeedPhrasePrivateKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to retrieve your wallet.
        /// </summary>
        internal static string txtImportSeedPhrasePrivateKey2 {
            get {
                return ResourceManager.GetString("txtImportSeedPhrasePrivateKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Seed Phrase or Private Key.
        /// </summary>
        internal static string txtImportSeedPrivateKay {
            get {
                return ResourceManager.GetString("txtImportSeedPrivateKay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve security with Password Update.
        /// </summary>
        internal static string txtImproveSecurity {
            get {
                return ResourceManager.GetString("txtImproveSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Confirmation.
        /// </summary>
        internal static string txtInvalidConfirmation {
            get {
                return ResourceManager.GetString("txtInvalidConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string txtLanguage {
            get {
                return ResourceManager.GetString("txtLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string txtLogin {
            get {
                return ResourceManager.GetString("txtLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string txtLogout {
            get {
                return ResourceManager.GetString("txtLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Sent Successful.
        /// </summary>
        internal static string txtMailSuccessful {
            get {
                return ResourceManager.GetString("txtMailSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MANAGE.
        /// </summary>
        internal static string txtMANAGE {
            get {
                return ResourceManager.GetString("txtMANAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY STAKING.
        /// </summary>
        internal static string txtMyStacking {
            get {
                return ResourceManager.GetString("txtMyStacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Wallets.
        /// </summary>
        internal static string txtMyWallet {
            get {
                return ResourceManager.GetString("txtMyWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        internal static string txtNewAccount {
            get {
                return ResourceManager.GetString("txtNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string txtNewPassword {
            get {
                return ResourceManager.GetString("txtNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Seed Phrase.
        /// </summary>
        internal static string txtNewSeedPhrase {
            get {
                return ResourceManager.GetString("txtNewSeedPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string txtNext {
            get {
                return ResourceManager.GetString("txtNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string txtNo {
            get {
                return ResourceManager.GetString("txtNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not now.
        /// </summary>
        internal static string txtNotNow {
            get {
                return ResourceManager.GetString("txtNotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kubh bh nhi.
        /// </summary>
        internal static string txtNull {
            get {
                return ResourceManager.GetString("txtNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string txtOk {
            get {
                return ResourceManager.GetString("txtOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string txtOldPassword {
            get {
                return ResourceManager.GetString("txtOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string txtPassword {
            get {
                return ResourceManager.GetString("txtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must have 8 character.
        /// </summary>
        internal static string txtPasswordAlert {
            get {
                return ResourceManager.GetString("txtPasswordAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to including alphanumeric.
        /// </summary>
        internal static string txtPasswordAlert2 {
            get {
                return ResourceManager.GetString("txtPasswordAlert2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        internal static string txtPasswordCapital {
            get {
                return ResourceManager.GetString("txtPasswordCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure to use a password you remember..
        /// </summary>
        internal static string txtPasswordPageText1 {
            get {
                return ResourceManager.GetString("txtPasswordPageText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otherwise you will need to restore the wallet from.
        /// </summary>
        internal static string txtPasswordPageText2 {
            get {
                return ResourceManager.GetString("txtPasswordPageText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your original seed phrase.
        /// </summary>
        internal static string txtPasswordPageText3 {
            get {
                return ResourceManager.GetString("txtPasswordPageText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string txtPeriod {
            get {
                return ResourceManager.GetString("txtPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Coin amount.
        /// </summary>
        internal static string txtPleaseEnterAmount {
            get {
                return ResourceManager.GetString("txtPleaseEnterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string txtPrint {
            get {
                return ResourceManager.GetString("txtPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click “Save Button” and keep secure by downloading  .
        /// </summary>
        internal static string txtPrintDescription1 {
            get {
                return ResourceManager.GetString("txtPrintDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your 24 words seed carefully. Anyone with access to your .
        /// </summary>
        internal static string txtPrintDescription2 {
            get {
                return ResourceManager.GetString("txtPrintDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recovery phrase could take your assets, store it securely. .
        /// </summary>
        internal static string txtPrintDescription3 {
            get {
                return ResourceManager.GetString("txtPrintDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do no keep a backup of your 24 worlds, if you lose it, .
        /// </summary>
        internal static string txtPrintDescription4 {
            get {
                return ResourceManager.GetString("txtPrintDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all coins in your wallet will be gone forever..
        /// </summary>
        internal static string txtPrintDescription5 {
            get {
                return ResourceManager.GetString("txtPrintDescription5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string txtPrivacyPolicy {
            get {
                return ResourceManager.GetString("txtPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste/type your private key.
        /// </summary>
        internal static string txtPrivateKeyEditor {
            get {
                return ResourceManager.GetString("txtPrivateKeyEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string txtProfile {
            get {
                return ResourceManager.GetString("txtProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECEIVE.
        /// </summary>
        internal static string txtRECEIVECapital {
            get {
                return ResourceManager.GetString("txtRECEIVECapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETRGSKJGHGHRNCH58JJHJK78JH.
        /// </summary>
        internal static string txtRequestWithdrawlAddress {
            get {
                return ResourceManager.GetString("txtRequestWithdrawlAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQUEST WITHDRAWL.
        /// </summary>
        internal static string txtRequestWithdrwalButton {
            get {
                return ResourceManager.GetString("txtRequestWithdrwalButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string txtRestore {
            get {
                return ResourceManager.GetString("txtRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        internal static string txtSAVE {
            get {
                return ResourceManager.GetString("txtSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string txtSaveChange {
            get {
                return ResourceManager.GetString("txtSaveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You understand that by saving this phrase you.
        /// </summary>
        internal static string txtSaveSeedAlert1 {
            get {
                return ResourceManager.GetString("txtSaveSeedAlert1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you already saved and continue.
        /// </summary>
        internal static string txtSaveSeedAlert3 {
            get {
                return ResourceManager.GetString("txtSaveSeedAlert3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can print at your own device CLICK OK if.
        /// </summary>
        internal static string txtSaveSeedeAlert2 {
            get {
                return ResourceManager.GetString("txtSaveSeedeAlert2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCAN.
        /// </summary>
        internal static string txtSCANCapital {
            get {
                return ResourceManager.GetString("txtSCANCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string txtSecurity {
            get {
                return ResourceManager.GetString("txtSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see all.
        /// </summary>
        internal static string txtSeeAll {
            get {
                return ResourceManager.GetString("txtSeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inadequate Data Entered !.
        /// </summary>
        internal static string txtSeedEntryError {
            get {
                return ResourceManager.GetString("txtSeedEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed Id.
        /// </summary>
        internal static string txtSeedId {
            get {
                return ResourceManager.GetString("txtSeedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEED PHRASE.
        /// </summary>
        internal static string txtSeedPhraseCapital {
            get {
                return ResourceManager.GetString("txtSeedPhraseCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste/type your seed phrase....
        /// </summary>
        internal static string txtSeedPhraseEditor {
            get {
                return ResourceManager.GetString("txtSeedPhraseEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Seed Phrase Entries !.
        /// </summary>
        internal static string txtSeedPhraseSave {
            get {
                return ResourceManager.GetString("txtSeedPhraseSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS IS YOUR.
        /// </summary>
        internal static string txtSeedTitle1 {
            get {
                return ResourceManager.GetString("txtSeedTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND.
        /// </summary>
        internal static string txtSENDCapital {
            get {
                return ResourceManager.GetString("txtSENDCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Funds.
        /// </summary>
        internal static string txtSendingFund {
            get {
                return ResourceManager.GetString("txtSendingFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Funds….
        /// </summary>
        internal static string txtSendingFunds {
            get {
                return ResourceManager.GetString("txtSendingFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        internal static string txtSETTING {
            get {
                return ResourceManager.GetString("txtSETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string txtSettings {
            get {
                return ResourceManager.GetString("txtSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Seed Phrase.
        /// </summary>
        internal static string txtShowSeedPhrase {
            get {
                return ResourceManager.GetString("txtShowSeedPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STAKE.
        /// </summary>
        internal static string txtSTAKE {
            get {
                return ResourceManager.GetString("txtSTAKE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETRGSKJGHGHRNCH58JJHJK78JH.
        /// </summary>
        internal static string txtStakeAddress {
            get {
                return ResourceManager.GetString("txtStakeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kskllslksdllkgXCVXCVXCVXCVXVXVkldgld.
        /// </summary>
        internal static string txtStakeAdress {
            get {
                return ResourceManager.GetString("txtStakeAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staked Amount.
        /// </summary>
        internal static string txtStakedAmount {
            get {
                return ResourceManager.GetString("txtStakedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STAKING.
        /// </summary>
        internal static string txtStakingCapital {
            get {
                return ResourceManager.GetString("txtStakingCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Staking Options.
        /// </summary>
        internal static string txtStakingOptions {
            get {
                return ResourceManager.GetString("txtStakingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string txtSubmit {
            get {
                return ResourceManager.GetString("txtSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success !.
        /// </summary>
        internal static string txtSuccessAlert {
            get {
                return ResourceManager.GetString("txtSuccessAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful !.
        /// </summary>
        internal static string txtSuccessful {
            get {
                return ResourceManager.GetString("txtSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string txtSupport {
            get {
                return ResourceManager.GetString("txtSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap as per your benefit and choice.
        /// </summary>
        internal static string txtSwapMessege {
            get {
                return ResourceManager.GetString("txtSwapMessege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWAPS.
        /// </summary>
        internal static string txtSWAPS {
            get {
                return ResourceManager.GetString("txtSWAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to Customer Care.
        /// </summary>
        internal static string txtTalkCustomerCare {
            get {
                return ResourceManager.GetString("txtTalkCustomerCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        internal static string txtTermOFServices {
            get {
                return ResourceManager.GetString("txtTermOFServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms Of Use.
        /// </summary>
        internal static string txtTerms {
            get {
                return ResourceManager.GetString("txtTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        internal static string txtTermsOfService {
            get {
                return ResourceManager.GetString("txtTermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        internal static string txtThankYou {
            get {
                return ResourceManager.GetString("txtThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total APR Received 10.000 DHN.
        /// </summary>
        internal static string txtTotalAPR {
            get {
                return ResourceManager.GetString("txtTotalAPR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total APR Received 00.000 DHN.
        /// </summary>
        internal static string txtTotalAPReceived {
            get {
                return ResourceManager.GetString("txtTotalAPReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total APR Received.
        /// </summary>
        internal static string txtTotalAprReceived {
            get {
                return ResourceManager.GetString("txtTotalAprReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trasaction on the way.
        /// </summary>
        internal static string txtTranferPopUp1 {
            get {
                return ResourceManager.GetString("txtTranferPopUp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can see it on explorer:.
        /// </summary>
        internal static string txtTranferPopUp2 {
            get {
                return ResourceManager.GetString("txtTranferPopUp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Transactions.
        /// </summary>
        internal static string txtTransactions {
            get {
                return ResourceManager.GetString("txtTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send &amp; receive funds.
        /// </summary>
        internal static string txtTransactTypeAlert {
            get {
                return ResourceManager.GetString("txtTransactTypeAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose if you want to send or receive funds.
        /// </summary>
        internal static string txtTransactTypeMessege {
            get {
                return ResourceManager.GetString("txtTransactTypeMessege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Details.
        /// </summary>
        internal static string txtTxDetail {
            get {
                return ResourceManager.GetString("txtTxDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE YOUR PASSWORD.
        /// </summary>
        internal static string txtTypePassword {
            get {
                return ResourceManager.GetString("txtTypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your profile here.
        /// </summary>
        internal static string txtUpdateProfile {
            get {
                return ResourceManager.GetString("txtUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        internal static string txtUSD {
            get {
                return ResourceManager.GetString("txtUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VeRocket.
        /// </summary>
        internal static string txtVeRocket {
            get {
                return ResourceManager.GetString("txtVeRocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-Click  Token Swap on VeChain.
        /// </summary>
        internal static string txtVeRocketInfo {
            get {
                return ResourceManager.GetString("txtVeRocketInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vexchange.
        /// </summary>
        internal static string txtVexchange {
            get {
                return ResourceManager.GetString("txtVexchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vexchange is a protocol for creating liquidity and trading VIP-180 tokens on VeChain.
        /// </summary>
        internal static string txtVexchangeInfo {
            get {
                return ResourceManager.GetString("txtVexchangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        internal static string txtWallet {
            get {
                return ResourceManager.GetString("txtWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Wallet Address .
        /// </summary>
        internal static string txtWalletAddresAlert {
            get {
                return ResourceManager.GetString("txtWalletAddresAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalletAddress.
        /// </summary>
        internal static string txtWalletAddress {
            get {
                return ResourceManager.GetString("txtWalletAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WALLET.
        /// </summary>
        internal static string txtWalletCapital {
            get {
                return ResourceManager.GetString("txtWalletCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Created .
        /// </summary>
        internal static string txtWalletCreated {
            get {
                return ResourceManager.GetString("txtWalletCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Name.
        /// </summary>
        internal static string txtWalletName {
            get {
                return ResourceManager.GetString("txtWalletName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet Restored.
        /// </summary>
        internal static string txtWalletRestored {
            get {
                return ResourceManager.GetString("txtWalletRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome !.
        /// </summary>
        internal static string txtWecomeText {
            get {
                return ResourceManager.GetString("txtWecomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME.
        /// </summary>
        internal static string txtWelcomeCapital {
            get {
                return ResourceManager.GetString("txtWelcomeCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string txtYes {
            get {
                return ResourceManager.GetString("txtYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By using the app, you agree to these terms and conditions.
        /// </summary>
        internal static string txtYouAreAgree {
            get {
                return ResourceManager.GetString("txtYouAreAgree", resourceCulture);
            }
        }
    }
}
