//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorhniiFoundationWallet.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DorhniiFoundationWallet.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password must be same..
        /// </summary>
        internal static string msgConfirmPassword {
            get {
                return ResourceManager.GetString("msgConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords fields cannot be empty..
        /// </summary>
        internal static string msgEmptyPasswords {
            get {
                return ResourceManager.GetString("msgEmptyPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection not found. Please check &amp; try again..
        /// </summary>
        internal static string msgNetworkIssueMessage {
            get {
                return ResourceManager.GetString("msgNetworkIssueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 8 characters, including letters and numbers..
        /// </summary>
        internal static string msgPasswordValidation {
            get {
                return ResourceManager.GetString("msgPasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed Phrase entry fields cannot be empty.
        /// </summary>
        internal static string msgSeedEntryError {
            get {
                return ResourceManager.GetString("msgSeedEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Save the Seed Phrase..
        /// </summary>
        internal static string msgSeedPhraseSave {
            get {
                return ResourceManager.GetString("msgSeedPhraseSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error occurred, please try again..
        /// </summary>
        internal static string msgTechnicalErrorOccurred {
            get {
                return ResourceManager.GetString("msgTechnicalErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stake.
        /// </summary>
        internal static string tstStake {
            get {
                return ResourceManager.GetString("tstStake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string txtAccounts {
            get {
                return ResourceManager.GetString("txtAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string txtAlert {
            get {
                return ResourceManager.GetString("txtAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APY,.
        /// </summary>
        internal static string txtApy {
            get {
                return ResourceManager.GetString("txtApy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string txtBack {
            get {
                return ResourceManager.GetString("txtBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string txtBalance {
            get {
                return ResourceManager.GetString("txtBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string txtConfirmPassword {
            get {
                return ResourceManager.GetString("txtConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string txtCreate {
            get {
                return ResourceManager.GetString("txtCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Password Fields.
        /// </summary>
        internal static string txtEmptyPasswords {
            get {
                return ResourceManager.GetString("txtEmptyPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        internal static string txtEnterPassword {
            get {
                return ResourceManager.GetString("txtEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Seed Phrase.
        /// </summary>
        internal static string txtEnterSeedPhrase {
            get {
                return ResourceManager.GetString("txtEnterSeedPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint and Face Id.
        /// </summary>
        internal static string txtFaceId {
            get {
                return ResourceManager.GetString("txtFaceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Fingerprint or Face ID.
        /// </summary>
        internal static string txtFingerprint {
            get {
                return ResourceManager.GetString("txtFingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Help.
        /// </summary>
        internal static string txtGetHelp {
            get {
                return ResourceManager.GetString("txtGetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Confirmation.
        /// </summary>
        internal static string txtInvalidConfirmation {
            get {
                return ResourceManager.GetString("txtInvalidConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string txtLanguage {
            get {
                return ResourceManager.GetString("txtLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string txtLogout {
            get {
                return ResourceManager.GetString("txtLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        internal static string txtNewAccount {
            get {
                return ResourceManager.GetString("txtNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Seed Phrase.
        /// </summary>
        internal static string txtNewSeedPhrase {
            get {
                return ResourceManager.GetString("txtNewSeedPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string txtNext {
            get {
                return ResourceManager.GetString("txtNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string txtOk {
            get {
                return ResourceManager.GetString("txtOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string txtPassword {
            get {
                return ResourceManager.GetString("txtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure to use a password you remember..
        /// </summary>
        internal static string txtPasswordPageText1 {
            get {
                return ResourceManager.GetString("txtPasswordPageText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otherwise you will need to restore the wallet from.
        /// </summary>
        internal static string txtPasswordPageText2 {
            get {
                return ResourceManager.GetString("txtPasswordPageText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your original seed phrase.
        /// </summary>
        internal static string txtPasswordPageText3 {
            get {
                return ResourceManager.GetString("txtPasswordPageText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string txtPeriod {
            get {
                return ResourceManager.GetString("txtPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string txtPrint {
            get {
                return ResourceManager.GetString("txtPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click “Print” and print out paper instructions and write down .
        /// </summary>
        internal static string txtPrintDescription1 {
            get {
                return ResourceManager.GetString("txtPrintDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your 24 words seed carefully. Anyone with access to your .
        /// </summary>
        internal static string txtPrintDescription2 {
            get {
                return ResourceManager.GetString("txtPrintDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recovery phrase could take your assets, strode it securely. .
        /// </summary>
        internal static string txtPrintDescription3 {
            get {
                return ResourceManager.GetString("txtPrintDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do no keep a backup of your 24 worlds, if you lose it, .
        /// </summary>
        internal static string txtPrintDescription4 {
            get {
                return ResourceManager.GetString("txtPrintDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all coins in your wallet will be gone forever..
        /// </summary>
        internal static string txtPrintDescription5 {
            get {
                return ResourceManager.GetString("txtPrintDescription5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string txtPrivacy {
            get {
                return ResourceManager.GetString("txtPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string txtProfile {
            get {
                return ResourceManager.GetString("txtProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string txtRestore {
            get {
                return ResourceManager.GetString("txtRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string txtSecurity {
            get {
                return ResourceManager.GetString("txtSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inadequate Data Entered !.
        /// </summary>
        internal static string txtSeedEntryError {
            get {
                return ResourceManager.GetString("txtSeedEntryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seed Id.
        /// </summary>
        internal static string txtSeedId {
            get {
                return ResourceManager.GetString("txtSeedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Seed Phrase Entries !.
        /// </summary>
        internal static string txtSeedPhraseSave {
            get {
                return ResourceManager.GetString("txtSeedPhraseSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string txtSettings {
            get {
                return ResourceManager.GetString("txtSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Seed Phrase.
        /// </summary>
        internal static string txtShowSeedPhrase {
            get {
                return ResourceManager.GetString("txtShowSeedPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staked Amount.
        /// </summary>
        internal static string txtStakedAmount {
            get {
                return ResourceManager.GetString("txtStakedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Staking Options.
        /// </summary>
        internal static string txtStakingOptions {
            get {
                return ResourceManager.GetString("txtStakingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string txtSupport {
            get {
                return ResourceManager.GetString("txtSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms Of Use.
        /// </summary>
        internal static string txtTerms {
            get {
                return ResourceManager.GetString("txtTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Transactions.
        /// </summary>
        internal static string txtTransactions {
            get {
                return ResourceManager.GetString("txtTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        internal static string txtWallet {
            get {
                return ResourceManager.GetString("txtWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your new wallet name.
        /// </summary>
        internal static string txtWalletName {
            get {
                return ResourceManager.GetString("txtWalletName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome !.
        /// </summary>
        internal static string txtWecomeText {
            get {
                return ResourceManager.GetString("txtWecomeText", resourceCulture);
            }
        }
    }
}
